### ISSUE TITLE
stegoVeritas integration

### ISSUE THREAD

**Issue by noraj** [Zeecka/AperiSolve#1]
Hi guys,

https://github.com/bannsec/stegoVeritas do automatic LSB bruteforce, extract trailing data, color map analysis, image transformation, data carving and extract frame for gif.

So I think you may be interested to include it in AperiSolve.

**Comment by Zeecka** [comment]
Hi,

Thanks for sharing, I knew the tool but did not use it very often. ZSteg already do automatic LSB bruteforce / extract. Color map analysis can be improved but I don't I'll implement stegoVeritas one for the moment. For the data carving part, I'll implement foremost/binwalk first. Finally for the gif part, the tools only work on the first frame (it's a choice I made due to the time of process). I'll have a look to stegoVeritas after foremost/binwalk implementation. If you really need the implementation of stegoVeritas, feel free to open a pull request ! Thanks, Zeecka

**Comment by noraj** [comment]
It was just an idea, most of the time I don't do stego, just when I solved all the Web in CTF :D
