### ISSUE TITLE
[Enhancement] Extracting thumbnail

### ISSUE THREAD

**Issue by wikijm** [Zeecka/AperiSolve#48]
Hi Zeecka,

Thanks a lot for your wonderful tool, and letting us playing with it through https://www.aperisolve.com!

Could you please consider extracting (and looping that task if thumbnail also contains a thumbnail) and show result on the WebGUI?

My assumption is, to identify that case we can use:

A) binwalk:

```
$ binwalk deeper.jpg
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             JPEG image data, JFIF standard 1.01
30            0x1E            TIFF image data, big-endian, offset of first image directory: 8
202           0xCA            JPEG image data, JFIF standard 1.01
232           0xE8            TIFF image data, big-endian, offset of first image directory: 8
404           0x194           JPEG image data, JFIF standard 1.01
```

On this example it seems that there is an another image on offset 404.

B) scalpel (an "apt install scalpel" do the trick to get it):
`scalpel mysteriousfile.jpg -o scalpel-output`
This command will export all image files into the folder "scalpel-output".

Let me know what you think, as there is probably a better way to answer my need 😉 

Regards,
WikiJM

**Comment by Zeecka** [comment]
Aperisolve aims to help people investigates, but making recursive search by it's own will result in a DOS of the webapp.

You can already download the extracted files under the binwalk results (including the thumbnail).
The feature you asked for is an equivalent of GIF image decomposition, extracting LSB encoded files, and so on ... Those images won't be displayed on the GUI for now mostly due to performances.

Note: this can be reproduce using dcode.fr image which contain "secret" thumbnail. https://www.dcode.fr/tools/exif-thumbnail/images/dcode-exif-thumbnail.jpg

**Comment by wikijm** [comment]
Understood, thanks for all the explanation.
Have a nice weekend 😄
